version: '3'
services:
  postgres:
    image: postgres:11-alpine
    env_file:
      - '.debug.env'
    ports:
      - 5432:5432
    volumes:
      - ./.debug/postgresql/data:/var/lib/postgresql/data
      - ./docker/dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
  mariadb:
    image: mariadb
    env_file:
      - '.debug.env'
    ports:
      - 3306:3306
    volumes:
      - ./.debug/mysql/data:/var/lib/mysql
