CREATE DATABASE starter_test;
GRANT ALL PRIVILEGES ON DATABASE starter_test TO postgres;

CREATE DATABASE starter_staging
GRANT ALL PRIVILEGES ON DATABASE starter_staging TO postgres;

CREATE DATABASE starter
GRANT ALL PRIVILEGES ON DATABASE starter TO postgres;